### ISSUE TITLE
only qualify the module if otherwise ambiguous

### ISSUE THREAD

**Issue by kohlhase** [jfschaefer/stextools#11]
`srify` generates term references like `\sn{foo?bar}` even if the refernce `bar` is unambiguous in this context. It would be nice to only generate `\sn{bar}` since this is shorter and more portable. It is clear that unqualified term references might become ambiguous later, but we can handle that with the VScode plugin in another annotation step.

**Comment by jfschaefer** [comment]
I now have two different strategies for handling this:
1. `cautious`: If there are several different symbols `foo` in the corpus, `foo` is added.
2. `minimal` (default): `foo` is omitted if there is no other symbol `foo` in context. This risks that future imports create ambiguity.

You can switch to cautious with `--disambiguation-policy=minimal` or by adding
```ini
[stextools.srify]
disambiguation-policy=minimal
```
to `~/.config/stextools/config.ini`

**Comment by jfschaefer** [comment]
Actually, after re-reading your post, I'll make `minimal` the default.
