### ISSUE TITLE
Allow to configure that some folders are not considered when computing the symbols. 

### ISSUE THREAD

**Issue by kohlhase** [jfschaefer/stextools#4]
There are some folders (e.g. `MathHub/sTeX`) that I keep around for reference, but I never want to annotate with symbols from them. I guess that should be in the configuration file. 

Also we should have an option to restrict the folders considered (e.g. `smglom`) when computing the annotations.

**Comment by jfschaefer** [comment]
For now, I've implemented this as command line arguments. Do you think a configuration file would be better?

Examples:
```bash
python3.9 -m stextools srify --filter=smglom/\* *.en.tex
python3.9 -m stextools srify --ignore=sTeX/\*,papers/\* *.en.tex
python3.9 -m stextools srify --filter=smglom/\* --ignore=smglom/mv *.en.tex
```

**Comment by kohlhase** [comment]
I think adding the pruning directories in the config (as well) would be better, since I never want to use the sTeX directory.

**Comment by jfschaefer** [comment]
Done you can now e.g. put
```ini
[stextools.srify]
ignore = sTeX/*
```
into `~/config/stextools/config.ini`
