### ISSUE TITLE
following inputref does not seem to work in a quiz

### ISSUE THREAD

**Issue by kohlhase** [jfschaefer/stextools#55]
I am using it on `MathHub/courses/FAU/AI/hwexam/source/WS2425/quizzes/quiz5.en.tex` and it does not seem to follow. (hwexam-private that is).

**Comment by jfschaefer** [comment]
This should be fixed with aa414a5188e88030bd93d83350bf57806b23e05b
During debugging, I discovered a deeper design flaw that I've also fixed.
It results in a slower start-up, unfortunately.
